[package]
edition = "2018"
name = "wasm"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["swc_v1"]
swc_v1 = []

plugin = ["getrandom/js", "turbopack-binding/__swc_core_binding_wasm_plugin"]

[dependencies]
anyhow = "1.0.82"
console_error_panic_hook = "0.1.7"
next-swc = { version = "0.0.0", path = "../core" }
once_cell = { workspace = true }
parking_lot_core = "=0.9.10"
path-clean = "1.0.1"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
tracing = { version = "0.1.40" }
wasm-bindgen = { version = "0.2.92", features = ["enable-interning"] }
wasm-bindgen-futures = "0.4.42"
getrandom = { version = "0.2.14", default-features = false, features = ["js"] }
js-sys = "0.3.69"
serde-wasm-bindgen = "0.6.5"
turbopack-binding = { workspace = true, features = [
  "__swc_core_binding_wasm",
  "__feature_mdx_rs",
] }
swc_core = { workspace = true, features = ["ecma_ast_serde", "common"] }


# Workaround a bug
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

# Workaround a bug
[package.metadata.wasm-pack.profile.dev]
wasm-opt = false
